/**
  \page orbit Basics of orbital mechanics

  This section of the manual contains a very brief summary of basic celestial mechanics.
  It is intended to clarify some of the concepts of various API functions in this reference
  document, but may also provide some useful general information for beginners.

  \section Contents
  \subpage orbit_1 \n
  \subpage orbit_2 \n
  \subpage orbit_3

  \page orbit_1 Elliptic orbits

  This page provides a summary of parameters for ideal 2-body orbital elements.

  <b>Conic section:</b> The trajectory of an object under the influence of the gravitational field generated by
  a point mass follows a conic section. This may be either periodic (closed circular
  or elliptic orbit) or nonperiodic (open parabolic or hyperbolic orbit).
  The equation of a conic section with the focus in the origin is given in polar coordinates by
  \f[
  r = \frac{p}{1+e \cos(\nu)}
  \f]
  with \e eccentricity e and <em>semi-latus rectum</em> p.

  <b>Standard gravitational parameter:</b> In the following, the standard gravitational
  parameter is defined as the product of the gravitational constant G and the mass M of the
  central body at focus F:
  \f[
   \mu = GM
  \f]

  \section ellips Elliptic orbits
  Elliptic (closed) orbits are characterised by an eccentricity e < 1. A special case are
  circular orbits (e = 0).

  \image html ellips.png "Elliptical orbit with central body at focus F"

  <b>Semi-major axis (a):</b> The longest semi-diameter of the ellipse. The distance from the
  centre (C) through one of the foci (F) to the edge of the ellipse (A). The semi-major
  axis can be calculated from the parameters of the conic section as
  \f[
  a = \frac{p}{1-e^2}
  \f]

  <b>Semi-minor axis (b):</b> The shortest semi-diameter of the ellipse. The distance from the
  centre (C) to the edge of the ellipse, at right angles to the major axis. The semi-minor
  axis can be calculated from the parameters of the conic section as
  \f[
  b = \frac{p}{\sqrt{1-e^2}} = a \sqrt{1-e^2}
  \f]

  <b>Periapsis:</b> The periapsis (A) (perigee for Earth orbits, perilune for lunar orbits) is
  the lowest point of the orbit, i.e. the point of the ellipse closest to focus F. The
  periapsis distance r<sub>pe</sub> = FA is given by
  \f[
  r_{\mathrm{pe}} = \frac{p}{1+e} = (1-e)a
  \f]

  <b>Apoapsis:</b> The apoapsis (B) (apogee for Earth orbits, apolune for lunar orbits) is
  the highest point of the orbit, i.e. the point of the ellipse farthest from focus F. The
  apoapsis distance r<sub>ap</sub> = FB is given by
  \f[
  r_{\mathrm{ap}} = \frac{p}{1-e} = (1+e)a
  \f]

  <b>True anomaly:</b> The true anomaly (v) of an orbiting object (P) is the angle AFP between
  P and periapsis A, measured at F.

  <b>Orbital period:</b> According to Kepler's third law, the square of the period T of an
  orbiting body is proportional to the cube of the semi-major axis a of the orbit. T is
  given by
  \f[
  T = 2\pi \sqrt{\frac{a^3}{\mu}}
  \f]

  <b>Orbital speed:</b> The orbital speed v as a function of radius r is given by
  \f[
  v = \sqrt{\mu\left(\frac{2}{r} - \frac{1}{a}\right)}
  \f]
  Maximum and minimum speed occur at periapsis and apoapsis, respectively:
  \f[
  v_\mathrm{pe} = \sqrt{\frac{(1+e)\mu}{(1-e)a}}, \qquad v_\mathrm{ap} = \sqrt{\frac{(1-e)\mu}{(1+e)a}}
  \f]
  The mean orbital speed is given by
  \f[
  \bar{v} = \frac{2\pi a}{T} = \sqrt{\frac{\mu}{a}} = na
  \f]

  where the mean angular motion <i>n</i> is defined as
  \f[
  n = \frac{2 \pi} {T}
  \f]

  <b>Specific orbital energy:</b> (or vis-viva energy) E is the sum of potential energy
  E<sub>p</sub> and kinetic energy E<sub>k</sub> of an orbiting body. E is constant along
  the orbit:
  \f[
  E = E_k + E_p = \frac{v^2}{2} - \frac{\mu}{r} = -\frac{1}{2} \frac{\mu^2}{h^2} (1-e^2)
  \f]
  where h is the specific angular momentum of the orbiting body.

  For specific types of orbit, E is given by
  \f[
  E = \left\lbrace \begin{array}{cll}
  -\frac{\mu}{2a} & \mathrm{if} & e < 1 \\
  0 & \mathrm{if} & e = 1 \\
  \frac{\mu}{2a} & \mathrm{if} & e > 1
  \end{array}\right.
  \f]

  \page orbit_2 The orbit in space

  The orientation of the orbital trajectory in space, relative to the reference body, is defined
  by three parameters (in addition to the two parameters describing the shape):
  - inclination
  - longitude of ascending node
  - longitude of periapsis

  The position of the orbiting object along the orbit is defined by an additional parameter, the
  true longitude.

  \image html orbit.png "The orbit in space"

  The orientation of an orbit in space is defined with respect to a frame of reference. For planetary
  orbits, the reference is usually given by the plane of the ecliptic and direction of the vernal equinox.
  For satellites in Earth orbit, the equatorial plane usually defines the reference plane.
  
  <b>Inclination</b>: The \e inclination i defines the tilt of the orbital plane against the reference
  plane. The intersection of the orbital plane with the reference plane is denoted as the
  <i>line of nodes</i>.
  
  <b>Ascending and descending node</b>: The line of nodes always passes through the orbit reference body (S).
  The \e nodes N<sub>1</sub> and N<sub>2</sub> are the points where the orbital trajectory intersects
  the reference plane. If the direction of orbit is such that the orbiting body passes the plane of the
  ecliptic from south to north at N<sub>1</sub>, then N<sub>1</sub> is the <i>ascending node</i>, and
  N<sub>2</sub> is the <i>descending node</i>.
  
  <b>Longitude of ascending node</b>: The angle between the reference direction \f$\Upsilon\f$ and node
  N<sub>1</sub> is the <i>longitude of the ascending node</i> (\f$\theta\f$).

  <b>Argument of periapsis</b>: The angle between node N<sub>1</sub> and periapsis A is the <i>argument
  of periapsis</i> (\f$\omega\f$).

  <b>Longitude of periapsis</b>: The sum \f$\varpi = \theta + \omega\f$ is called the <i>longitude of
  periapsis</i>.

  <b>True longitude</b>: The sum of longitude of periapsis and true anomaly,
  \f[
  L = \varpi + \nu = \theta + \omega + \nu
  \f]
  is called the <i>true longitude</i> of the orbiting body.

  \section meanlong Mean longitude

  Consider a vector originating in S and moving in the plane of the orbit with mean angular velocity \e n,
  passing through point A at time t<sub>0</sub>.

  <b>Mean anomaly</b>: At time t, the vector is located at <i>mean anomaly</i> \f$ M = n(t-t_0) \f$
  relative to periapsis A.

  <b>Mean longitude</b>: The <i>mean longitude</i> of the orbiting body is the sum of mean anomaly and
  longitude of periapsis:
  \f[
  l = \theta + \omega + n(t-t_0) = \varpi + n(t-t_0)
  \f]
  The <i>mean longitude at the epoch</i> is defined as the mean longitude at t=0, given by
  \f[
  \varepsilon = \varpi - nt_0
  \f]
  The mean longitude can then be written as
  \f[
  l = nt + \varepsilon.
  \f]
  The mean anomaly is given by
  \f[
  M = n(t-t_0) = l - \varpi = nt + \varepsilon - \varpi
  \f]
  
  \page orbit_3 Kepler's equation

  \section meananm True and eccentric anomaly
  To find the position P of an orbiting body at some time t, we need to find its
  true anomaly \f$\nu\f$ at that time. Calculating true anomaly is not trivial
  for eccentric orbits, because the velocity of the orbiting body is continually
  changing.

  <b>Eccentric anomaly</b>: Define a circle with radius <i>a</i> (semi-major axis
  of the orbit ellipse) whose centre coincides with the centre of the ellipse.
  Project object position P perpendicular to the semi-major axis onto the circle
  (Q). Then the <i>eccentric anomaly</i> E is defined as the angle ACQ between
  periapsis A and Q, measured at the centre C of the circle.

  \image html ellips2.png Geometric interpretation of the eccentric anomaly (E).

  The relationship between orbit radius r and eccentric anomaly E is given by
  \f[
  r = a(1-e \cos E)
  \f]
  The relationship between true anomaly \f$\nu\f$ and E is given by
  \f[
  \tan \frac{\nu}{2} = \sqrt{ \frac{1+e}{1-e}} \tan \frac{E}{2}
  \f]
  With these equations, position P can be calculated when eccentric anomaly E is
  known. E is calculated for a given time t by solving <i>Kepler's equation</i>.

  \section kepler Kepler's equation
  Consider a vector rotating around C at constant angular velocity n, given by
  the orbiter's mean motion. If the vector passes A at time t<sub>0</sub>, then
  its angle with A at time t is given by
  \f[
  M(t) = n(t-t_0)
  \f]
  M is called the <i>mean anomaly</i>. Kepler's equation defines a relation
  between mean anomaly M and eccentric anomaly E:
  \f[
  E(t) - e \sin E(t) = M(t) = n(t-t_0)
  \f]
  It cannot be solved for E in closed form, and must generally be
  solved iteratively.

  */