note = oapi.create_annotation()
note:set_pos (0.3,0.1,0.8,0.95)
note:set_colour ({r=1,g=0.6,b=0.2})

note:set_text('This scenario demonstrates the use of the Shuttle ascent autopilot in Orbiter.')
proc.wait_simdt(5)
note:set_text('The autopilot is accessed via the AscentAP MFD mode, already activated in the left MFD.')
proc.wait_simdt(10)
note:set_text('We first need to set the parameters of the orbit.')
proc.wait_simdt(5)
note:set_text('Adjust the altitude of the target circular orbit with AL- and AL+.')
proc.wait_simdt(3)
proc.wait_frames(500, function() oapi.simulatebufferedkey(OAPI_KEY.MINUS, OAPI_KEY.LSHIFT) end)
proc.wait_simdt(2)
note:set_text('Adjust the launch azimuth (the initial heading) with AZ- and AZ+. The launch azimuth determines the inclination of the final orbit, which must be matched with the rendezvous target.')
proc.wait_simdt(3)
proc.wait_frames(300, function() oapi.simulatebufferedkey(OAPI_KEY.SEMICOLON, OAPI_KEY.LSHIFT) end)
proc.wait_simdt(2)
note:set_text('Wait for your launch window, then press L to initiate the launch sequence.')
oapi.simulatebufferedkey(OAPI_KEY.L, OAPI_KEY.LSHIFT)
proc.wait_simdt(10)
note:set_text('Watch the Shuttle make its way to orbit.')