#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_D3D9CREDITS                         101
#define IDD_D3D9MESHDEBUG                       102
#define IDD_D3D9SCATTER                         103
#define IDD_D3D9SETUP                           104
#define IDS_INFO                                1000
#define IDS_TYPE                                1001
#define IDC_AA                                  2000
#define IDC_AF                                  2001
#define IDC_ATD_AUX1                            2002
#define IDC_ATD_AUX2                            2003
#define IDC_ATD_AUX3                            2004
#define IDC_ATD_AUX4                            2005
#define IDC_ATD_BALANCE                         2006
#define IDC_ATD_BLUE                            2007
#define IDC_ATD_DEPTH                           2008
#define IDC_ATD_EXPO                            2009
#define IDC_ATD_GREEN                           2010
#define IDC_ATD_HEIGHT                          2011
#define IDC_ATD_IN                              2012
#define IDC_ATD_MIE                             2013
#define IDC_ATD_MOFFSET                         2014
#define IDC_ATD_MPHASE                          2015
#define IDC_ATD_MPOW                            2016
#define IDC_ATD_OUT                             2017
#define IDC_ATD_RED                             2018
#define IDC_ATD_RPHASE                          2019
#define IDC_ATD_RPOW                            2020
#define IDC_ATM_AUX1                            2022
#define IDC_ATM_AUX2                            2023
#define IDC_ATM_AUX3                            2024
#define IDC_ATM_AUX4                            2025
#define IDC_ATM_BALANCE                         2026
#define IDC_ATM_BLUE                            2027
#define IDC_ATM_DEPTH                           2028
#define IDC_ATM_EXPO                            2029
#define IDC_ATM_GREEN                           2030
#define IDC_ATM_HEIGHT                          2031
#define IDC_ATM_IN                              2032
#define IDC_ATM_LOAD                            2033
#define IDC_ATM_MIE                             2034
#define IDC_ATM_MODE                            2035
#define IDC_ATM_MOFFSET                         2036
#define IDC_ATM_MPHASE                          2037
#define IDC_ATM_MPOW                            2038
#define IDC_ATM_OUT                             2039
#define IDC_ATM_RED                             2040
#define IDC_ATM_RPHASE                          2041
#define IDC_ATM_RPOW                            2042
#define IDC_ATM_SAVE                            2043
#define IDC_BASEVIS                             2044
#define IDC_CONVERGENCE                         2045
#define IDC_CONV_DSP                            2046
#define IDC_CREDITS                             2047
#define IDC_CREDITSTEXT                         2048
#define IDC_DBG_ALPHA                           2049
#define IDC_DBG_AMBIENT                         2050
#define IDC_DBG_BLUE                            2051
#define IDC_DBG_BOXES                           2052
#define IDC_DBG_CAMERA                          2053
#define IDC_DBG_COPY                            2054
#define IDC_DBG_DISPLAY                         2055
#define IDC_DBG_DUAL                            2056
#define IDC_DBG_ENVMAP                          2057
#define IDC_DBG_FPSLIM                          2058
#define IDC_DBG_GREEN                           2059
#define IDC_DBG_GROUP                           2060
#define IDC_DBG_GRPDN                           2061
#define IDC_DBG_GRPO                            2062
#define IDC_DBG_GRPUP                           2063
#define IDC_DBG_HSG                             2064
#define IDC_DBG_HSM                             2065
#define IDC_DBG_LINK                            2066
#define IDC_DBG_MATADJ                          2067
#define IDC_DBG_MATEFF                          2068
#define IDC_DBG_MATGRP                          2069
#define IDC_DBG_MATPRP                          2070
#define IDC_DBG_MATSAVE                         2071
#define IDC_DBG_MESH                            2072
#define IDC_DBG_MESHNAME                        2073
#define IDC_DBG_MSHDN                           2074
#define IDC_DBG_MSHO                            2075
#define IDC_DBG_MSHUP                           2076
#define IDC_DBG_PASTE                           2077
#define IDC_DBG_PICK                            2078
#define IDC_DBG_RED                             2079
#define IDC_DBG_REFLMAP                         2080
#define IDC_DBG_RTGT                            2081
#define IDC_DBG_SPEED                           2082
#define IDC_DBG_SPEEDDSP                        2083
#define IDC_DBG_SPHERES                         2084
#define IDC_DBG_TEXTURE                         2085
#define IDC_DBG_TILES                           2086
#define IDC_DBG_VISO                            2087
#define IDC_DBG_VISUAL                          2088
#define IDC_DBG_WIRE                            2089
#define IDC_DEBUG                               2090
#define IDC_DEMAND                              2091
#define IDC_DEVICE                              2092
#define IDC_ENVFACES                            2093
#define IDC_ENVMODE                             2094
#define IDC_FONT                                2095
#define IDC_GEOMETRY                            2096
#define IDC_GLASSSHADE                          2097
#define IDC_HZ                                  2098
#define IDC_LODBIAS                             2099
#define IDC_MESH_DEBUGGER                       2100
#define IDC_NEARPLANE                           2101
#define IDC_NORMALMAPS                          2102
#define IDC_PLANETGLOW                          2103
#define IDC_SEPARATION                          2104
#define IDC_SEPA_DSP                            2105
#define IDC_SRFPRELOAD                          2107
#define IDC_SYMBOLIC                            2108
#define IDC_ATM_COPYTO                          2109
#define IDC_SUNBRIGHTNESS                       2110
#define IDC_POSTPROCESS                         2111
#define IDC_CAMMODE                             2112
