#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_D3D9SETUP                           103
#define IDD_D3D9CREDITS                         106
#define IDD_D3D9MESHDEBUG                       112
#define IDS_INFO                                1000
#define IDS_TYPE                                1001
#define IDC_STATIC1                             1300
#define IDC_STATIC2                             1301
#define IDC_STATIC3                             1302
#define IDC_STATIC4                             1303
#define IDC_STATIC5                             1304
#define IDC_STATIC6                             1305
#define IDC_CREDITSTEXT                         40000
#define IDC_DBG_DUAL                            40001
#define IDC_DBG_WIRE                            40002
#define IDC_DBG_ENVMAP                          40003
#define IDC_DBG_MATGRP                          40004
#define IDC_DBG_MATPRP                          40005
#define IDC_SYMBOLIC                            40009
#define IDC_NEARPLANE                           40010
#define IDC_STATIC7                             40011
#define IDC_DEVICE                              40012
#define IDC_FONT                                40013
#define IDC_SHADER                              40014
#define IDC_DEBUG                               40015
#define IDC_DEMAND                              40016
#define IDC_HZ                                  40017
#define IDC_AA                                  40018
#define IDC_AF                                  40019
#define IDC_BASEVIS                             40020
#define IDC_NORMALMAPS                          40021
#define IDC_CREDITS                             40026
#define IDC_SRFPRELOAD                          40027
#define IDC_DBG_GROUP                           40041
#define IDC_DBG_HSG                             40042
#define IDC_DBG_HSM                             40043
#define IDC_DBG_BOXES                           40045
#define IDC_DBG_SPHERES                         40046
#define IDC_DBG_GRPO                            40047
#define IDC_DBG_MSHO                            40048
#define IDC_DBG_TILES                           40049
#define IDC_DBG_RTGT                            40050
#define IDC_DBG_VISUAL                          40051
#define IDC_DBG_CAMERA                          40052
#define IDC_DBG_DISPLAY                         40053
#define IDC_DBG_MSHUP                           40060
#define IDC_DBG_MSHDN                           40061
#define IDC_DBG_GRPUP                           40062
#define IDC_DBG_GRPDN                           40063
#define IDC_CONVERGENCE                         40067
#define IDC_SEPARATION                          40068
#define IDC_CONV_DSP                            40069
#define IDC_SEPA_DSP                            40070
#define IDC_DBG_AMBIENT                         40071
#define IDC_DBG_MESH                            40072
#define IDC_DBG_VISO                            40073
#define IDC_DBG_SPEED                           40074
#define IDC_DBG_SPEEDDSP                        40075
#define IDC_DBG_MATEFF                          40083
#define IDC_DBG_RED                             40084
#define IDC_DBG_GREEN                           40085
#define IDC_DBG_BLUE                            40086
#define IDC_DBG_ALPHA                           40087
#define IDC_DBG_MATADJ                          40088
#define IDC_DBG_MATSAVE                         40089
#define IDC_ENVMODE                             40090
#define IDC_STATIC8                             40091
#define IDC_STATIC9                             40093
#define IDC_ENVFACES                            40094
#define IDC_DBG_TEXTURE                         40096
#define IDC_DBG_PICK                            40098
