//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Orbiter.rc
//
#include "resource_video.h"

#define LAUNCHPAD_WIN_WIDTH             400

#define IDS_STRING1                     1
#define IDS_TABSCENARIO                 2
#define IDS_TABPARAMS                   3
#define IDS_TABVISUAL                   4
#define IDS_TABMODULE                   5
#define IDS_TABVIDEO                    6
#define IDS_TABJOYSTICK                 7
#define IDS_TABEXTRA                    8
#define IDS_TABABOUT                    9
#define IDI_MAIN_ICON                   101
#define IDR_MAIN_ACCEL                  113
#define IDD_MAIN                        171
#define IDD_PAGE_SCN                    172
#define IDD_PAGE_OPT                    173
#define IDD_PAGE_MOD                    174
#define IDD_PAGE_JOY                    175
#define IDD_PAGE_EXT                    176
#define IDD_PAGE_ABT                    177
#define IDD_SAVESCN                     181
#define IDD_CAMERA                      182
#define IDD_CAM_PG_TARGET               184
#define IDD_CAM_PG_VIEW                 185
#define IDD_CAM_PG_GROUND               186
#define IDD_CAM_PG_PRESET               188
#define IDD_CAM_PG_CONTROL              189
#define IDD_JUMPVESSEL                  190
#define IDD_TIMEWARP                    191
#define IDI_ICON1                       193
#define IDB_BITMAP2                     194
#define IDD_MSG                         199
#define IDT_CONTRIB                     200
#define IDT_DISCLAIMER                  201
#define IDD_NAVAID                      201
#define IDT_CREDIT                      202
#define IDD_MAP                         202
#define IDD_CUSTOMCMD                   205
#define IDB_TREEICON_FOLDER1            206
#define IDB_TREEICON_FOLDER2            207
#define IDB_TREEICON_SCN1               208
#define IDB_TREEICON_SCN2               209
#define IDD_OPTIONS                     210
#define IDD_OPTIONS_CELSPHERE           211
#define IDD_OPTIONS_VISHELPER           212
#define IDD_OPTIONS_PLANETARIUM         213
#define IDD_OPTIONS_LABELS              214
#define IDD_OPTIONS_BODYFORCE           215
#define IDD_OPTIONS_FRAMEAXES           216
#define IDD_OPTIONS_INSTRUMENT          217
#define IDD_OPTIONS_UI                  218
#define IDD_OPTIONS_JOYSTICK            219
#define IDD_OPTIONS_VESSEL              220
#define IDD_OPTIONS_VISUAL              221
#define IDD_OPTIONS_PHYSICS             222
#define IDD_DEMOBK                      223
#define IDD_ORBITERHELP                 224
#define IDD_HELP                        225
#define IDB_ICON64                      229
#define IDB_DEFBUTTON                   235
#define IDD_MSG_FRECORDER               241
#define IDD_RECPLAY                     242
#define IDI_STOP_ICON                   245
#define IDI_REC_ICON                    246
#define IDB_DNARROW                     249
#define IDB_UPARROW                     251
#define IDD_EXTRA_DYNAMICS              252
#define IDD_EXTRA_STABILISATION         253
#define IDD_EXTRA_ADYNAMICS             254
#define IDD_EXTRA_FIXEDSTEP             255
#define IDD_EXTRA_SHUTDOWN              256
#define IDD_SERVER                      257
#define IDD_RECPLAY_ANNOTATE            258
#define IDD_PLAYBACK_EDITOR             258
#define IDD_PBEDITOR_NOTE               259
#define IDD_PBEDITOR_GENERIC            260
#define IDD_PBEDITOR_TACC               261
#define IDD_PBEDITOR_CAMPRESET          262
#define IDD_PBEDITOR_NOTEPOS            263
#define IDD_PBEDITOR_NOTECOL            264
#define IDD_PBEDITOR_NOTESIZE           265
#define IDB_BANNER                      266
#define IDD_PAGE_WAIT1                  266
#define IDD_PAGE_WAIT2                  266
#define IDB_LOGO_NG                     266
#define IDB_BITMAP3                     267
#define IDB_SHADOW                      267
#define IDB_BITMAP4                     270
#define IDD_EXTRA_PLANETRENDER          271
#define IDD_EXTRA_TIMER                 272
#define IDB_BITMAP5                     273
#define IDI_LEFTARROW                   278
#define IDI_RIGHTARROW                  279
#define IDI_RIGHTARROW1                 280
#define IDI_DRIGHTARROW                 280
#define IDD_MENU_CONFIG                 280
#define IDD_EXTRA_TIMER1                281
#define IDD_EXTRA_PERFORMANCE           281
#define IDD_EXTRA_MFDCONFIG             282
#define IDD_CAPTURE                     283
#define IDD_OBJINFO                     284
#define IDD_DIALOG1                     285
#define IDB_ARROWS                      286
#define IDI_DDOWN                       288
#define IDI_ICON2                       289
#define IDI_DUP                         289
#define IDI_FINGER                      290
#define IDI_FINGER1                     291
#define IDI_CROSS                       291
#define IDD_MAP_CONFIG                  291
#define IDI_FINGER2                     292
#define IDR_IMAGE1                      292
#define IDI_LARROW                      293
#define IDI_RARROW                      294
#define IDD_EXTRA_LOGFILE               294
#define IDI_UARROW                      295
#define IDI_UARROW1                     296
#define IDI_DARROW                      296
#define IDI_UARROW_TILT                 297
#define IDI_DARROW1                     298
#define IDI_DARROW_TILT                 298
#define IDI_LARROW_TILT                 299
#define IDD_CAM_PG_FOV_DBG              300
#define IDD_CAM_PG_FOV                  300
#define IDI_RARROW_TILT                 300
#define IDD_EXTRA_PERFORMANCE1          301
#define IDD_EXTRA_LAUNCHPAD             301
#define IDD_EXTRA_DBGRENDER             302
#define IDLAUNCH                        1000
#define IDEXIT                          1001
#define IDC_MAINTAB                     1002
#define IDC_MSG                         1050

#define IDC_MOD_ACTGRP                  1500
#define IDC_MOD_INFO                    1501
#define IDC_MOD_TREE                    1502
#define IDC_MOD_DEACTALL                1503
#define IDC_MOD_SPLIT1                  1504
#define IDC_MOD_BUTTON1                 1505
#define IDC_MOD_BUTTON2                 1506

#define IDC_VID_LABEL_MODULE            1600
#define IDC_VID_COMBO_MODULE            1601
#define IDC_VID_STATIC1                 1623
#define IDC_VID_STATIC2                 1624
#define IDC_VID_STATIC3                 1625
#define IDC_VID_MODULE_INFO             1626

#define IDC_ABT_CREDIT                  1700
#define IDC_ABT_WEB                     1701
#define IDC_ABT_CONTRIB                 1702
#define IDC_ABT_DISCLAIM                1703
#define IDC_ABT_TXT_BUILDDATE           1704
#define IDC_ABT_GRP_ORBITER             1705
#define IDC_ABT_GRP_WEB                 1706
#define IDC_ABT_ICON_DG                 1707
#define IDC_ABT_TXT_NAME                1708
#define IDC_ABT_TXT_WEB                 1709
#define IDC_ABT_TXT_WEBADDR             1710
#define IDC_ABT_TXT_CPR                 1711
#define IDC_ABT_TXT_LICENSE             1712
#define IDC_ABT_GRP_COMPONENT           1713
#define IDC_ABT_LBOX_COMPONENT          1714

// Inline option dialog controls
#define IDC_OPT_PAGELIST                1000
#define IDC_OPT_PAGECONTAINER           1001
#define IDC_OPT_SPLIT                   1002
#define IDC_OPT_CSP_ENABLESTARPIX       1003
#define IDC_OPT_CSP_STARMAGHI           1004
#define IDC_OPT_CSP_STARMAGHISPIN       1005
#define IDC_OPT_CSP_STARMAGLO           1006
#define IDC_OPT_CSP_STARMAGLOSPIN       1007
#define IDC_OPT_CSP_STARMINBRT          1008
#define IDC_OPT_CSP_STARMINBRTSPIN      1009
#define IDC_OPT_CSP_STARMAPLIN          1010
#define IDC_OPT_CSP_STARMAPEXP          1011
#define IDC_OPT_CSP_ENABLESTARMAP       1012
#define IDC_OPT_CSP_STARMAPIMAGE        1013
#define IDC_OPT_CSP_ENABLEBKGMAP        1014
#define IDC_OPT_CSP_BKGIMAGE            1015
#define IDC_OPT_CSP_BGBRIGHTNESS        1016
#define IDC_OPT_VHELP_PLN               1017
#define IDC_OPT_VHELP_MKR               1018
#define IDC_OPT_VHELP_VEC               1019
#define IDC_OPT_VHELP_CRD               1020
#define IDC_OPT_PLN                     1021
#define IDC_OPT_PLN_CELGRID             1022
#define IDC_OPT_PLN_ECLGRID             1023
#define IDC_OPT_PLN_GALGRID             1024
#define IDC_OPT_PLN_HRZGRID             1025
#define IDC_OPT_PLN_EQU                 1026
#define IDC_OPT_PLN_CNSTLABEL           1027
#define IDC_OPT_PLN_CNSTLABEL_FULL      1028
#define IDC_OPT_PLN_CNSTLABEL_SHORT     1029
#define IDC_OPT_PLN_CNSTBND             1030
#define IDC_OPT_PLN_CNSTPATTERN         1031
#define IDC_OPT_PLN_MARKER              1032
#define IDC_OPT_PLN_MKRLIST             1033
#define IDC_OPT_MKR                     1034
#define IDC_OPT_MKR_VESSEL              1035
#define IDC_OPT_MKR_CELBODY             1036
#define IDC_OPT_MKR_FEATUREBODY         1037
#define IDC_OPT_MKR_BASE                1038
#define IDC_OPT_MKR_BEACON              1039
#define IDC_OPT_MKR_FEATURES            1040
#define IDC_OPT_MKR_FEATURELIST         1041
#define IDC_OPT_VEC                     1042
#define IDC_OPT_VEC_WEIGHT              1043
#define IDC_OPT_VEC_THRUST              1044
#define IDC_OPT_VEC_LIFT                1045
#define IDC_OPT_VEC_DRAG                1046
#define IDC_OPT_VEC_TOTAL               1047
#define IDC_OPT_VEC_TORQUE              1048
#define IDC_OPT_VEC_LINSCL              1049
#define IDC_OPT_VEC_LOGSCL              1050
#define IDC_OPT_VEC_SCALE               1051
#define IDC_OPT_VEC_OPACITY             1052
#define IDC_OPT_CRD                     1053
#define IDC_OPT_CRD_VESSEL              1054
#define IDC_OPT_CRD_CELBODY             1055
#define IDC_OPT_CRD_BASE                1056
#define IDC_OPT_CRD_NEGATIVE            1057
#define IDC_OPT_CRD_SCALE               1058
#define IDC_OPT_CRD_OPACITY             1059
#define IDC_OPT_MFD_INTERVAL            1060
#define IDC_OPT_MFD_INTERVALSPIN        1061
#define IDC_OPT_MFD_SIZE                1062
#define IDC_OPT_MFD_SIZESPIN            1063
#define IDC_OPT_MFD_TRANSP              1064
#define IDC_OPT_MFD_VCTEXSIZE           1065
#define IDC_OPT_PANEL_SCROLLSPEED       1066
#define IDC_OPT_PANEL_SCROLLSPEEDSPIN   1067
#define IDC_OPT_PANEL_SCALE             1068
#define IDC_OPT_PANEL_SCALESPIN         1069
#define IDC_OPT_UI_MOUSEFOCUSMODE       1070
#define IDC_OPT_VESSEL_FUELLIMIT        1071
#define IDC_OPT_VESSEL_PADFUEL          1072
#define IDC_OPT_VESSEL_COMPLEXMODEL     1073
#define IDC_OPT_VESSEL_DAMAGE           1074
#define IDC_OPT_VIS_CLOUD               1075
#define IDC_OPT_VIS_CSHADOW             1076
#define IDC_OPT_VIS_HAZE                1077
#define IDC_OPT_VIS_FOG                 1078
#define IDC_OPT_VIS_REFWATER            1079
#define IDC_OPT_VIS_RIPPLE              1080
#define IDC_OPT_VIS_LIGHTS              1081
#define IDC_OPT_VIS_LTLEVEL             1082
#define IDC_OPT_VIS_ELEV                1083
#define IDC_OPT_VIS_ELEVMODE            1084
#define IDC_OPT_VIS_MAXLEVEL            1085
#define IDC_OPT_VIS_VSHADOW             1086
#define IDC_OPT_VIS_REENTRY             1087
#define IDC_OPT_VIS_SHADOW              1088
#define IDC_OPT_VIS_PARTICLE            1089
#define IDC_OPT_VIS_SPECULAR            1090
#define IDC_OPT_VIS_LOCALLIGHT          1091
#define IDC_OPT_VIS_AMBIENT             1092
#define IDC_OPT_PHYS_COMPLEXGRAV        1093
#define IDC_OPT_PHYS_RPRESSURE          1094
#define IDC_OPT_PHYS_DISTMASS           1095
#define IDC_OPT_PHYS_WIND               1096
#define IDC_OPT_JOY_DEVICE              1097
#define IDC_OPT_JOY_THROTTLE            1098
#define IDC_OPT_JOY_INIT                1099
#define IDC_OPT_JOY_SAT                 1100
#define IDC_OPT_JOY_DEAD                1101
#define IDC_OPT_JOY_STATIC1             1102
#define IDC_OPT_JOY_STATIC2             1103
#define IDC_OPT_JOY_STATIC3             1104
#define IDC_OPT_JOY_STATIC4             1105

// Unsorted
#define IDC_SCN_LIST                    1090
#define IDC_SCN_DESC                    1091
#define IDC_SCN_PAUSED                  1092
#define IDC_SCN_SAVE                    1093
#define IDC_SAVE_NAME                   1094
#define IDC_SCN_DELQS                   1095
#define IDC_SAVE_DESC                   1096
#define IDC_SCN_INFO                    1097
#define IDC_SCN_HTML                    1098
#define IDC_TREE1                       1113
#define IDC_EDIT1                       1118
#define IDC_EDIT2                       1119
#define IDC_EDIT3                       1120
#define IDC_EDIT4                       1121
#define IDC_INFO_TEXT                   1121
#define IDC_EDIT5                       1122
#define IDC_NET_SEARCH                  1122
#define IDC_EDIT6                       1123
#define IDC_EDIT7                       1124
#define IDC_EDIT8                       1125
#define IDC_MAP_ZOOMOUT                 1125
#define IDC_EDIT9                       1126
#define IDC_NET_PAGE2                   1126
#define IDC_BUTTON1                     1127
#define IDC_BUTTON2                     1128
#define IDC_BUTTON3                     1129
#define IDC_NET_JOIN                    1129
#define IDC_BUTTON4                     1130
#define IDC_BUTTON5                     1131
#define IDC_BUTTON6                     1132
#define IDC_MAP_ZOOMIN                  1132
#define IDC_BUTTON7                     1133
#define IDC_BUTTON8                     1134
#define IDC_BUTTON9                     1135
#define IDC_NET_PAGE1                   1145
#define IDC_NET_CREATE                  1147
#define IDC_SLIDER1                     1148
#define IDC_NET_SESSION                 1149
#define IDC_SLIDER2                     1150
#define IDC_NET_MAXPLAYER               1151
#define IDC_SLIDER3                     1151
#define IDC_VESSEL                      1154
#define IDC_COMBO1                      1155
#define IDC_COMBO2                      1156
#define IDC_COMBO3                      1157
#define IDC_INFO_TYPE                   1157
#define IDC_COMBO4                      1158
#define IDC_COMBO5                      1159
#define IDC_MAP_REFERENCE               1159
#define IDC_COMBO6                      1160
#define IDC_INFO_NAME                   1161
#define IDC_MAP                         1162
#define IDC_MAP_TRACK                   1163
#define IDC_LIST1                       1165
#define IDC_IMG                         1189
#define IDC_CUSTOM1                     1190
#define IDC_TAB1                        1192
#define IDC_LOGO                        1216
#define IDC_CHECK1                      1224
#define IDC_CHECK2                      1225
#define IDC_CHECK3                      1226
#define IDC_CHECK4                      1227
#define IDC_CHECK5                      1228
#define IDC_CHECK6                      1229
#define IDC_MAPOPT_VORS                 1229
#define IDC_EXT_TEXT                    1231
#define IDC_EXT_LIST                    1232
#define IDC_STAB_ENABLE                 1240
#define IDC_EXT_OPEN                    1243
#define IDC_EDIT10                      1244
#define IDC_EDIT11                      1245
#define IDC_EDIT12                      1246
#define IDC_RADIO1                      1247
#define IDC_RADIO2                      1248
#define IDC_RADIO3                      1249
#define IDC_RADIO4                      1250
#define IDC_RADIO5                      1251
#define IDC_RADIO6                      1252
#define IDC_RADIO7                      1253
#define IDC_RADIO8                      1254
#define IDC_SPIN1                       1256
#define IDC_EVTIME                      1257
#define IDC_SPIN2                       1258
#define IDC_SPIN3                       1259
#define IDC_MNU_SCN                     1259
#define IDC_SPIN4                       1260
#define IDC_MNU_OPT                     1260
#define IDC_MNU_MOD                     1261
#define IDC_MNU_VID                     1262
#define IDC_MNU_EXT                     1263
#define IDC_MNU_ABT                     1264
#define IDC_SHADOW                      1267
#define IDC_BLACKBOX                    1268
#define IDC_MNU_PAGECONTAINER           1269
#define IDC_OPT_STATIC1                 1270
#define IDC_OPT_STATIC2                 1271
#define IDC_DEV_STATIC3                 1288
#define IDB_CLOSEDOWN2                  1289
#define IDC_WAITTEXT                    1290
#define IDC_PROGRESS1                   1291
#define IDC_CUSTOM2                     1292
#define IDC_SCN_SPLIT1                  1292
#define IDC_LIST2                       1298
#define IDC_BGINTENS                    1310
#define IDC_RICHEDIT21                  1340
#define IDC_INFOBOX                     1340
#define IDC_INFOLIST                    1342
#define IDC_INFO_DDN                    1343
#define IDC_INFO_DUP                    1344
#define IDC_MAP_ZOOM                    1347
#define IDC_MAP_ZOOMBOX                 1348
#define IDC_MAP_DRAG                    1349
#define IDC_MAP_SELECT                  1350
#define IDC_MAP_FINDTYPE                1351
#define IDC_MAP_INFO                    1352
#define IDC_MAPOPT_VESSELALL            1353
#define IDC_MAPOPT_VESSELFOCUS          1354
#define IDC_MAPOPT_VESSELNONE           1355
#define IDC_MAPOPT_ORBITPLANE           1356
#define IDC_MAPOPT_ORBITGTRACK          1357
#define IDC_MAPOPT_HORIZON              1359
#define IDC_MAPOPT_LANDMARKS            1360
#define IDC_MAPOPT_GRIDLINES            1361
#define IDC_MAPOPT_COASTLINES           1362
#define IDC_MAPOPT_CONTOURS             1363
#define IDC_MAPOPT_BASES                1364
#define IDC_MAP_OPTIONS                 1365
#define IDC_MAPOPT_TLINE                1367
#define IDC_MAPOPT_TSHADE               1368
#define IDC_MAPOPT_ORBITFOCUS           1369
#define IDC_MAPOPT_ORBITSEL             1370
#define IDC_MAP_FINDNAME                1371
#define IDC_MAPOPT_SATELLITES           1372
#define IDC_INFO_MAP                    1373
#define IDC_CUSTOM5                     1395
#define IDC_EXT_SPLIT1                  1397
#define IDC_VERSION                     1401
#define IDC_PAUSEINDICATOR              1402

#define IDC_STATIC1						10000
#define IDC_STATIC2                     10001
#define IDC_STATIC3                     10002
#define IDC_STATIC4                     10003
#define IDC_STATIC5                     10004
#define IDC_STATIC6                     10005
#define IDC_STATIC7                     10006
#define IDC_STATIC8                     10007
#define IDC_STATIC9                     10008
#define IDC_STATIC10                    10009
#define IDC_STATIC11                    10010
#define IDC_STATIC12                    10011
#define IDC_STATIC13                    10012

#define IDC_SCROLLBAR1                  10100
#define IDC_SCROLLBAR2                  10101

#define IDM_EXIT                        40001
#define IDM_CHANGEDEVICE                40010
#define IDM_TOGGLEFULLSCREEN            40011
#define IDM_HELP                        40012
#define IDM_TOGGLESTART                 40013
#define IDM_SINGLESTEP                  40014
#define IDM_ABOUT                       40028

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        295
#define _APS_NEXT_COMMAND_VALUE         40037
#define _APS_NEXT_CONTROL_VALUE         1403
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
