//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Orbiter.rc
//
#define IDS_STRING1                     1
#define IDR_RT_MANIFEST1                1
#define IDS_TABSCENARIO                 2
#define IDS_TABPARAMS                   3
#define IDS_TABVISUAL                   4
#define IDS_TABMODULE                   5
#define IDS_TABVIDEO                    6
#define IDS_TABJOYSTICK                 7
#define IDS_TABEXTRA                    8
#define IDS_TABABOUT                    9
#define IDI_MAIN_ICON                   101
#define IDI_MAIN_ICON_BAK               102
#define IDR_MAIN_ACCEL                  113
#define IDR_MENU                        143
#define IDR_POPUP                       145
#define IDB_LOGO                        152
#define IDD_MAIN                        171
#define IDD_PAGE_FIRST                  172
#define IDD_PAGE_SCN                    172
#define IDD_PAGE_OPT                    173
#define IDD_PAGE_VIS                    174
#define IDD_PAGE_MOD                    175
#define IDD_PAGE_DEV                    176
#define IDD_PAGE_JOY                    177
#define IDD_PAGE_EXT                    178
#define IDD_PAGE_ABT                    179
#define IDD_PAGE_NET                    180
#define IDD_SAVESCN                     181
#define IDD_CAMERA                      182
#define IDD_CAM_PG_TARGET               184
#define IDD_CAM_PG_VIEW                 185
#define IDD_CAM_PG_GROUND               186
#define IDD_CAM_PG_PRESET               188
#define IDD_CAM_PG_CONTROL              189
#define IDD_JUMPVESSEL                  190
#define IDD_TIMEWARP                    191
#define IDB_BITMAP1                     192
#define IDI_ICON1                       193
#define IDB_BITMAP2                     194
#define IDD_NET_CREATE                  198
#define IDD_MSG                         199
#define IDT_CONTRIB                     200
#define IDT_DISCLAIMER                  201
#define IDD_NAVAID                      201
#define IDT_CREDIT                      202
#define IDD_MAP                         202
#define IDD_PAGE_NET2                   203
#define IDD_PAGE_NET3                   204
#define IDD_CUSTOMCMD                   205
#define IDB_TREEICON_FOLDER1            206
#define IDB_TREEICON_FOLDER2            207
#define IDB_TREEICON_SCN1               208
#define IDB_TREEICON_SCN2               209
#define IDD_DEMOBK                      223
#define IDD_ORBITERHELP                 224
#define IDD_HELP                        225
#define IDD_CUSTOMLABELS                227
#define IDD_CUSTOMCLABELS               228
#define IDB_ICON64                      229
#define IDD_VISHELPER                   230
#define IDD_VHELP_BODYFORCE             231
#define IDD_VHELP_PLANETARIUM           232
#define IDD_VHELP_COORDINATES           233
#define IDB_DEFBUTTON                   235
#define IDD_MSG_FRECORDER               241
#define IDD_RECPLAY                     242
#define IDI_STOP_ICON                   245
#define IDI_REC_ICON                    246
#define IDB_DNARROW                     249
#define IDB_UPARROW                     251
#define IDD_EXTRA_DYNAMICS              252
#define IDD_EXTRA_STABILISATION         253
#define IDD_EXTRA_ADYNAMICS             254
#define IDD_EXTRA_FIXEDSTEP             255
#define IDD_EXTRA_SHUTDOWN              256
#define IDD_SERVER                      257
#define IDD_RECPLAY_ANNOTATE            258
#define IDD_PLAYBACK_EDITOR             258
#define IDD_PBEDITOR_NOTE               259
#define IDD_PBEDITOR_GENERIC            260
#define IDD_PBEDITOR_TACC               261
#define IDD_PBEDITOR_CAMPRESET          262
#define IDD_PBEDITOR_NOTEPOS            263
#define IDD_PBEDITOR_NOTECOL            264
#define IDD_PBEDITOR_NOTESIZE           265
#define IDB_BANNER                      266
#define IDD_PAGE_WAIT1                  266
#define IDD_PAGE_WAIT2                  266
#define IDB_LOGO_NG                     266
#define IDB_BITMAP3                     267
#define IDB_SHADOW                      267
#define IDB_BITMAP4                     270
#define IDD_EXTRA_PLANETRENDER          271
#define IDD_EXTRA_TIMER                 272
#define IDB_BITMAP5                     273
#define IDI_LEFTARROW                   278
#define IDI_RIGHTARROW                  279
#define IDI_RIGHTARROW1                 280
#define IDI_DRIGHTARROW                 280
#define IDD_MENU_CONFIG                 280
#define IDD_EXTRA_TIMER1                281
#define IDD_EXTRA_PERFORMANCE           281
#define IDD_EXTRA_MFDCONFIG             282
#define IDD_CAPTURE                     283
#define IDD_OBJINFO                     284
#define IDD_DIALOG1                     285
#define IDB_ARROWS                      286
#define IDI_DDOWN                       288
#define IDI_ICON2                       289
#define IDI_DUP                         289
#define IDI_FINGER                      290
#define IDI_FINGER1                     291
#define IDI_CROSS                       291
#define IDD_MAP_CONFIG                  291
#define IDI_FINGER2                     292
#define IDR_IMAGE1                      292
#define IDI_LARROW                      293
#define IDI_RARROW                      294
#define IDD_DIALOG2                     294
#define IDD_EXTRA_LOGFILE               294
#define IDI_UARROW                      295
#define IDI_UARROW1                     296
#define IDI_DARROW                      296
#define IDI_UARROW_TILT                 297
#define IDI_DARROW1                     298
#define IDI_DARROW_TILT                 298
#define IDI_LARROW_TILT                 299
#define IDD_CAM_PG_FOV_DBG              300
#define IDD_CAM_PG_FOV                  300
#define IDI_RARROW_TILT                 300
#define IDD_EXTRA_PERFORMANCE1          301
#define IDD_EXTRA_LAUNCHPAD             301
#define IDD_EXTRA_DBGRENDER             302
#define IDLAUNCH                        1000
#define IDEXIT                          1001
#define IDC_MAINTAB                     1002
#define IDC_VID_DEVICE                  1019
#define IDC_VID_FULL                    1020
#define IDC_VID_WINDOW                  1021
#define IDC_VID_STATIC5                 1022
#define IDC_VID_STATIC6                 1023
#define IDC_VID_MODE                    1024
#define IDC_VID_BPP                     1025
#define IDC_VID_VSYNC                   1026
#define IDC_VID_PAGEFLIP                1027
#define IDC_VID_STATIC7                 1028
#define IDC_VID_STATIC8                 1029
#define IDC_VID_STATIC9                 1030
#define IDC_VID_WIDTH                   1031
#define IDC_VID_HEIGHT                  1032
#define IDC_VID_ASPECT                  1033
#define IDC_VID_4X3                     1034
#define IDC_JOY_STATIC1                 1034
#define IDC_VID_16X10                   1035
#define IDC_JOY_DEVICE                  1035
#define IDC_VID_16X9                    1036
#define IDC_JOY_STATIC2                 1036
#define IDC_VID_ENUM                    1037
#define IDC_JOY_STATIC3                 1037
#define IDC_VID_INFO                    1038
#define IDC_JOY_STATIC4                 1038
#define IDC_JOY_STATIC5                 1039
#define IDC_JOY_THROTTLE                1040
#define IDC_JOY_DEAD                    1041
#define IDC_JOY_SAT                     1042
#define IDC_JOY_INIT                    1043
#define IDC_MSG                         1050
#define IDC_OPT_COMPLEXMODEL            1051
#define IDC_OPT_DAMAGE                  1052
#define IDC_OPT_LIMFUEL                 1053
#define IDC_OPT_PADFUEL                 1054
#define IDC_OPT_COMPLEXGRAV             1055
#define IDC_OPT_RPRESSURE               1056
#define IDC_OPT_DISTMASS                1057
#define IDC_OPT_WIND                    1058
#define IDC_OPT_MFDTRANSP               1059
#define IDC_OPT_REFRESH                 1060
#define IDC_OPT_MFDSIZE                 1061
#define IDC_OPT_PANELSCALE              1062
#define IDC_OPT_PANELSPD                1063
#define IDC_OPT_MAGHI                   1064
#define IDC_OPT_MAGLO                   1065
#define IDC_OPT_BRTLO                   1066
#define IDC_VIS_CLOUD                   1067
#define IDC_VIS_REFWATER                1068
#define IDC_VIS_HAZE                    1069
#define IDC_VIS_LIGHTS                  1070
#define IDC_VIS_LTLEVEL                 1071
#define IDC_VIS_SHADOW                  1072
#define IDC_VIS_VSHADOW                 1073
#define IDC_VIS_SPECULAR                1074
#define IDC_VIS_AMBIENT                 1075
#define IDC_VIS_LOCALLIGHT              1076
#define IDC_VIS_REENTRY                 1077
#define IDC_VIS_CSHADOW                 1078
#define IDC_VIS_PARTICLE                1079

#define IDC_ABT_CREDIT                  1500
#define IDC_ABT_WEB                     1501
#define IDC_ABT_CONTRIB                 1502
#define IDC_ABT_DISCLAIM                1503
#define IDC_ABT_TXT_BUILDDATE           1504
#define IDC_ABT_GRP_ORBITER             1505
#define IDC_ABT_GRP_WEB                 1506
#define IDC_ABT_ICON_DG                 1507
#define IDC_ABT_TXT_NAME                1508
#define IDC_ABT_TXT_WEB                 1509
#define IDC_ABT_TXT_WEBADDR             1510
#define IDC_ABT_TXT_CPR                 1511
#define IDC_ABT_TXT_LICENSE             1512
#define IDC_ABT_GRP_COMPONENT           1513
#define IDC_ABT_LBOX_COMPONENT          1514

#define IDC_SCN_STATIC1                 1087
#define IDC_SCN_LIST                    1090
#define IDC_SCN_DESC                    1092
#define IDC_SCN_PAUSED                  1093
#define IDC_SCN_SAVE                    1094
#define IDC_SAVE_NAME                   1095
#define IDC_SCN_DELQS                   1096
#define IDC_SAVE_DESC                   1097
#define IDC_SCN_INFO                    1098
#define IDC_MOD_ACTLIST                 1100
#define IDC_MOD_INACTLIST               1101
#define IDC_MOD_DEACTSEL                1102
#define IDC_MOD_DEACTALL                1103
#define IDC_MOD_ACTSEL                  1104
#define IDC_TREE1                       1113
#define IDC_EDIT1                       1118
#define IDC_EDIT2                       1119
#define IDC_EDIT3                       1120
#define IDC_EDIT4                       1121
#define IDC_INFO_TEXT                   1121
#define IDC_EDIT5                       1122
#define IDC_NET_SEARCH                  1122
#define IDC_EDIT6                       1123
#define IDC_EDIT7                       1124
#define IDC_EDIT8                       1125
#define IDC_MAP_ZOOMOUT                 1125
#define IDC_EDIT9                       1126
#define IDC_NET_PAGE2                   1126
#define IDC_BUTTON1                     1127
#define IDC_BUTTON2                     1128
#define IDC_BUTTON3                     1129
#define IDC_NET_JOIN                    1129
#define IDC_BUTTON4                     1130
#define IDC_BUTTON5                     1131
#define IDC_BUTTON6                     1132
#define IDC_MAP_ZOOMIN                  1132
#define IDC_BUTTON7                     1133
#define IDC_BUTTON8                     1134
#define IDC_BUTTON9                     1135
#define IDC_NET_PAGE1                   1145
#define IDC_NET_CREATE                  1147
#define IDC_SLIDER1                     1148
#define IDC_NET_SESSION                 1149
#define IDC_SLIDER2                     1150
#define IDC_NET_MAXPLAYER               1151
#define IDC_SLIDER3                     1151
#define IDC_VESSEL                      1154
#define IDC_COMBO1                      1155
#define IDC_CLBL_OBJECT                 1155
#define IDC_COMBO2                      1156
#define IDC_COMBO3                      1157
#define IDC_INFO_TYPE                   1157
#define IDC_COMBO4                      1158
#define IDC_COMBO5                      1159
#define IDC_MAP_REFERENCE               1159
#define IDC_COMBO6                      1160
#define IDC_STATIC1                     1161
#define IDC_INFO_NAME                   1161
#define IDC_STATIC2                     1162
#define IDC_MAP                         1162
#define IDC_STATIC3                     1163
#define IDC_MAP_TRACK                   1163
#define IDC_STATIC4                     1164
#define IDC_STATIC5                     1165
#define IDC_LIST1                       1165
#define IDC_STATIC6                     1166
#define IDC_OPT_FOCUS                   1166
#define IDC_STATIC7                     1167
#define IDC_STATIC8                     1168
#define IDC_STATIC9                     1169
#define IDC_STATIC10                    1170
#define IDC_PLANETARIUM                 1170
#define IDC_PLN_CELGRID                 1171
#define IDC_STATIC11                    1171
#define IDC_PLN_ECLGRID                 1172
#define IDC_STATIC12                    1172
#define IDC_STATIC13                    1173
#define IDC_PLN_ECLIPTIC                1173
#define IDC_PLN_EQUATOR                 1174
#define IDC_PLN_CONST                   1175
#define IDC_PLN_CNSTLABEL               1176
#define IDC_PLN_CMARKER                 1177
#define IDC_PLN_VMARKER                 1178
#define IDC_PLN_BMARKER                 1179
#define IDC_PLN_RMARKER                 1180
#define IDC_PLN_LMARKER                 1181
#define IDC_PLN_CCMARKER                1182
#define IDC_PLN_CONFIG                  1183
#define IDC_PLN_CONFIG2                 1184
#define IDC_PLN_FULL                    1185
#define IDC_PLN_SHORT                   1186
#define IDC_VID_STENCIL                 1188
#define IDC_IMG                         1189
#define IDC_CUSTOM1                     1190
#define IDC_CLBL_LIST                   1191
#define IDC_TAB1                        1192
#define IDC_BODYFORCE                   1194
#define IDC_WEIGHT                      1195
#define IDC_THRUST                      1196
#define IDC_LIFT                        1197
#define IDC_DRAG                        1198
#define IDC_TOTAL                       1199
#define IDC_TORQUE                      1200
#define IDC_LINSCALE                    1201
#define IDC_LOGSCALE                    1202
#define IDC_SCALE                       1204
#define IDC_OPACITY                     1205
#define IDC_COORDINATES                 1206
#define IDC_CRD_VESSEL                  1207
#define IDC_CRD_CBODY                   1208
#define IDC_CRD_BASE                    1209
#define IDC_CRD_NEGATIVE                1210
#define IDC_CRD_SCALE                   1211
#define IDC_CRD_OPAC                    1212
#define IDC_VIS_RIPPLE                  1214
#define IDC_VIS_MAXLEVEL                1215
#define IDC_LOGO                        1216
#define IDC_CHECK1                      1224
#define IDC_CHECK2                      1225
#define IDC_CHECK3                      1226
#define IDC_CHECK4                      1227
#define IDC_CHECK5                      1228
#define IDC_CHECK6                      1229
#define IDC_MAPOPT_VORS                 1229
#define IDC_EXT_TEXT                    1231
#define IDC_EXT_LIST                    1232
#define IDC_STAB_ENABLE                 1240
#define IDC_EXT_OPEN                    1243
#define IDC_EDIT10                      1244
#define IDC_EDIT11                      1245
#define IDC_EDIT12                      1246
#define IDC_RADIO1                      1247
#define IDC_RADIO2                      1248
#define IDC_RADIO3                      1249
#define IDC_RADIO4                      1250
#define IDC_RADIO5                      1251
#define IDC_RADIO6                      1252
#define IDC_RADIO7                      1253
#define IDC_RADIO8                      1254
#define IDC_SPIN1                       1256
#define IDC_EVTIME                      1257
#define IDC_SPIN2                       1258
#define IDC_SPIN3                       1259
#define IDC_MNU_SCN                     1259
#define IDC_SPIN4                       1260
#define IDC_MNU_PRM                     1260
#define IDC_MNU_VIS                     1261
#define IDC_MNU_MOD                     1262
#define IDC_MNU_VID                     1263
#define IDC_MNU_JOY                     1264
#define IDC_MNU_EXT                     1265
#define IDC_MNU_ABT                     1266
#define IDC_SHADOW                      1267
#define IDC_MOD_ACTGRP                  1267
#define IDC_BLACKBOX                    1268
#define IDC_MOD_INACTGRP                1268
#define IDC_OPT_STATIC1                 1270
#define IDC_OPT_STATIC2                 1271
#define IDC_OPT_STATIC3                 1272
#define IDC_OPT_STATIC4                 1273
#define IDC_OPT_STATIC5                 1274
#define IDC_OPT_STATIC6                 1275
#define IDC_OPT_STATIC7                 1276
#define IDC_OPT_STATIC8                 1277
#define IDC_OPT_STATIC9                 1278
#define IDC_OPT_STATIC10                1279
#define IDC_OPT_STATIC11                1280
#define IDC_VIS_STATIC1                 1281
#define IDC_OPT_STATIC14                1281
#define IDC_VIS_STATIC2                 1282
#define IDC_VIS_STATIC3                 1283
#define IDC_VIS_STATIC4                 1284
#define IDC_VIS_STATIC5                 1285
#define IDC_VID_STATIC1                 1286
#define IDC_VID_STATIC2                 1287
#define IDC_DEV_STATIC3                 1288
#define IDC_VID_STATIC3                 1288
#define IDB_CLOSEDOWN2                  1289
#define IDC_WAITTEXT                    1290
#define IDC_PROGRESS1                   1291
#define IDC_CUSTOM2                     1292
#define IDC_SCN_SPLIT1                  1292
#define IDC_OPT_STATIC12                1293
#define IDC_OPT_STATIC13                1294
#define IDC_VIS_FOG                     1297
#define IDC_LIST2                       1298
#define IDC_MOD_INFO                    1304
#define IDC_VIS_STATIC6                 1305
#define IDC_VIS_BGIMAGE                 1307
#define IDC_VIS_STATIC7                 1308
#define IDC_VIS_STATIC8                 1309
#define IDC_BGINTENS                    1310
#define IDC_VIS_BGINTENS                1310
#define IDC_RICHEDIT21                  1340
#define IDC_INFOBOX                     1340
#define IDC_INFOLIST                    1342
#define IDC_INFO_DDN                    1343
#define IDC_INFO_DUP                    1344
#define IDC_MAP_ZOOM                    1347
#define IDC_MAP_ZOOMBOX                 1348
#define IDC_MAP_DRAG                    1349
#define IDC_MAP_SELECT                  1350
#define IDC_MAP_FINDTYPE                1351
#define IDC_MAP_INFO                    1352
#define IDC_MAPOPT_VESSELALL            1353
#define IDC_MAPOPT_VESSELFOCUS          1354
#define IDC_MAPOPT_VESSELNONE           1355
#define IDC_MAPOPT_ORBITPLANE           1356
#define IDC_MAPOPT_ORBITGTRACK          1357
#define IDC_MAPOPT_HORIZON              1359
#define IDC_MAPOPT_LANDMARKS            1360
#define IDC_MAPOPT_GRIDLINES            1361
#define IDC_MAPOPT_COASTLINES           1362
#define IDC_MAPOPT_CONTOURS             1363
#define IDC_MAPOPT_BASES                1364
#define IDC_MAP_OPTIONS                 1365
#define IDC_MAPOPT_TLINE                1367
#define IDC_MAPOPT_TSHADE               1368
#define IDC_MAPOPT_ORBITFOCUS           1369
#define IDC_MAPOPT_ORBITSEL             1370
#define IDC_MAP_FINDNAME                1371
#define IDC_MAPOPT_SATELLITES           1372
#define IDC_INFO_MAP                    1373
#define IDC_CUSTOM5                     1395
#define IDC_SCN_HTML                    1395
#define IDC_MOD_SPLIT1                  1396
#define IDC_EXT_SPLIT1                  1397
#define IDC_VIS_ELEV                    1399
#define IDC_VIS_ELEVMODE                1400
#define IDC_VERSION                     1401
#define IDC_PAUSEINDICATOR              1402
#define IDM_EXIT                        40001
#define IDM_CHANGEDEVICE                40010
#define IDM_TOGGLEFULLSCREEN            40011
#define IDM_HELP                        40012
#define IDM_TOGGLESTART                 40013
#define IDM_SINGLESTEP                  40014
#define IDM_ABOUT                       40028

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        295
#define _APS_NEXT_COMMAND_VALUE         40037
#define _APS_NEXT_CONTROL_VALUE         1403
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
