//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScnEditor.rc
//
#define IDS_ERR1                        1
#define IDS_ERR2                        2
#define IDS_ERR3                        3
#define IDS_ERR4                        4
#define IDS_PROP1                       5
#define IDS_PROP2                       6
#define IDS_PROP3                       7
#define IDS_PROP4                       8
#define IDD_EDITOR                      101
#define IDD_TAB_VESSEL                  102
#define IDD_TAB_NEW                     103
#define IDD_TAB_SAVE                    104
#define IDB_PAUSE                       104
#define IDD_TAB_EDIT1                   105
#define IDB_TREEICON_FOLDER1            105
#define IDD_TAB_EDIT2                   106
#define IDB_TREEICON_FOLDER2            106
#define IDD_TAB_EDIT3                   107
#define IDD_TAB_EDIT4                   108
#define IDB_TREEICON_FILE1              108
#define IDD_TAB_EDIT5                   109
#define IDB_TREEICON_FILE2              109
#define IDD_TAB_EDIT6                   110
#define IDD_TAB_EDIT7                   111
#define IDD_TAB_EDIT8                   112
#define IDD_TAB_DATE                    113
#define IDS_INFO                        1000
#define IDS_TYPE                        1001
#define IDPAUSE                         1002
#define IDC_BACK                        1003
#define IDC_APPLY                       1004
#define IDC_REFRESH                     1005
#define IDC_SAVE                        1006
#define IDC_VESSELNEW                   1007
#define IDC_VESSELDEL                   1008
#define IDC_VESSELEDIT                  1009
#define IDC_ELEMENTS                    1010
#define IDC_DATE                        1010
#define IDC_STATEVEC                    1011
#define IDC_ORIENT                      1012
#define IDC_ANGVEL                      1013
#define IDC_GROUND                      1014
#define IDC_PROPELLANT                  1015
#define IDC_DOCKING                     1016
#define IDC_EXTRA1                      1017
#define IDC_EXTRA2                      1018
#define IDC_EXTRA3                      1019
#define IDC_EXTRA4                      1020
#define IDC_EXTRA5                      1021
#define IDC_EXTRA6                      1022
#define IDC_LIST1                       1023
#define IDC_COMBO1                      1024
#define IDC_COMBO2                      1025
#define IDC_COMBO3                      1026
#define IDC_COMBO4                      1027
#define IDC_COMBO5                      1028
#define IDC_COMBO6                      1029
#define IDC_EDIT1                       1030
#define IDC_EDIT2                       1031
#define IDC_EDIT3                       1032
#define IDC_EDIT4                       1033
#define IDC_EDIT5                       1034
#define IDC_EDIT6                       1035
#define IDC_EDIT7                       1036
#define IDC_SPIN1                       1037
#define IDC_SPIN2                       1038
#define IDC_SPIN3                       1039
#define IDC_SPIN4                       1040
#define IDC_SPIN5                       1041
#define IDC_SPIN6                       1042
#define IDC_SPIN1A                      1043
#define IDC_SPIN2A                      1044
#define IDC_SPIN3A                      1045
#define IDC_STATIC1                     1046
#define IDC_STATIC2                     1047
#define IDC_STATIC3                     1048
#define IDC_STATIC4                     1049
#define IDC_STATIC5                     1050
#define IDC_STATIC6                     1051
#define IDC_STATIC1A                    1052
#define IDC_STATIC2A                    1053
#define IDC_STATIC3A                    1054
#define IDC_STATIC4A                    1055
#define IDC_STATIC5A                    1056
#define IDC_STATIC6A                    1057
#define IDC_KILLROT                     1058
#define IDC_SPIN4A                      1058
#define IDC_CREATE                      1059
#define IDC_SPIN5A                      1059
#define IDC_REF                         1060
#define IDC_FRM                         1061
#define IDC_PERIOD                      1062
#define IDC_SPIN6A                      1062
#define IDC_PERIAPSIS                   1063
#define IDC_APOAPSIS                    1064
#define IDC_PET                         1065
#define IDC_APT                         1066
#define IDC_MNANM                       1067
#define IDC_TRANM                       1068
#define IDC_MNLNG                       1069
#define IDC_TRLNG                       1070
#define IDC_CRD                         1071
#define IDC_NAME                        1072
#define IDC_FOCUS                       1073
#define IDC_CAMERA                      1074
#define IDC_BASE                        1075
#define IDC_PAD                         1076
#define IDC_TRACK                       1077
#define IDC_PROPLEVEL                   1078
#define IDC_EMPTYALL                    1079
#define IDC_FULLALL                     1080
#define IDC_EMPTY                       1081
#define IDC_FULL                        1082
#define IDC_UNDOCK                      1084
#define IDC_IDS                         1085
#define IDC_DOCK                        1086
#define IDC_ERRMSG                      1087
#define IDC_RADIO1                      1088
#define IDC_RADIO2                      1089
#define IDC_STATECPY                    1091
#define IDC_UT_DAY                      1092
#define IDC_UT_MONTH                    1093
#define IDC_UT_YEAR                     1094
#define IDC_UT_HOUR                     1095
#define IDC_UT_MIN                      1096
#define IDC_UT_SEC                      1097
#define IDC_MJD                         1098
#define IDC_JD                          1099
#define IDC_JC2000                      1100
#define IDC_EPOCH                       1101
#define IDC_SPIN_DAY                    1102
#define IDC_SPIN_MONTH                  1103
#define IDC_SPIN_YEAR                   1104
#define IDC_SPIN_HOUR                   1105
#define IDC_SPIN_MINUTE                 1106
#define IDC_SPIN_SECOND                 1107
#define IDC_PROP_ORBITAL                1108
#define IDC_PROP_SORBITAL               1109
#define IDC_NOW                         1110
#define IDC_VESSELBMP                   1111
#define IDC_VESSELTP                    1112
#define IDC_BUTTON1                     1123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
